"""Regenerate zip3-contacts.js from the team-maintained spreadsheet.

Source: part 2/spreadsheets/zip3_congress_contacts.csv (one row per ZIP3
prefix; House rep names like "Jane Doe (D)" and their contact pages,
semicolon-separated when the ZIP3 spans multiple districts).

Run from this folder:  python make_zip3_contacts.py
"""
import csv, json, re, os

SRC = os.path.join(os.path.dirname(__file__), "..", "..", "part 2", "spreadsheets", "zip3_congress_contacts.csv")
OUT = os.path.join(os.path.dirname(__file__), "zip3-contacts.js")

table = {}
for row in csv.DictReader(open(SRC, encoding="utf-8-sig")):
    names = [n.strip() for n in (row["House_Reps"] or "").split(";") if n.strip()]
    urls = [u.strip() for u in (row["House_Rep_Contact_Pages"] or "").split(";") if u.strip()]
    if not names or len(names) != len(urls):
        continue
    reps = []
    for name, url in zip(names, urls):
        m = re.match(r"^(.*?)\s*\(([^)]+)\)\s*$", name)
        reps.append({
            "n": (m.group(1) if m else name),
            "p": (m.group(2) if m else ""),
            "u": url,
        })
    table[row["ZIP3"]] = {"s": (row["States"] or "").strip(), "r": reps}

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Generated by make_zip3_contacts.py from part 2/spreadsheets/zip3_congress_contacts.csv\n")
    f.write("   — do not edit by hand. ZIP3 -> {s: state(s), r: [{n: name, p: party, u: contact page}]} */\n")
    f.write("var ZIP3_CONTACTS = ")
    json.dump(table, f, ensure_ascii=False, separators=(",", ":"))
    f.write(";\n")

print(f"wrote {OUT}: {len(table)} ZIP3 entries")
